export const DESIGN_WIDTH = 112;
export const DESIGN_HEIGHT = 388;
export const VIEWPORT_PADDING_X = 16;
export const VIEWPORT_PADDING_Y = 22;

const TRAFFIC_LIGHT_VISUAL_HEIGHT = 246;
const STATUS_LABEL_VISUAL_HEIGHT = 12;
const SETUP_NOTICE_VISUAL_HEIGHT = 42;
const SOUND_TOGGLE_VISUAL_HEIGHT = 22;
const STACK_GAP = 12;
const FRAME_VERTICAL_PADDING = 22;

export const MINIMUM_REQUIRED_HEIGHT =
  TRAFFIC_LIGHT_VISUAL_HEIGHT +
  STATUS_LABEL_VISUAL_HEIGHT +
  SETUP_NOTICE_VISUAL_HEIGHT +
  SOUND_TOGGLE_VISUAL_HEIGHT +
  STACK_GAP +
  FRAME_VERTICAL_PADDING;
